M48
; DRILL file {KiCad 7.0.2} date Thu Oct 26 15:36:31 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-26T15:36:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.829Y-3.1239
T2
X4.122Y-1.5118
X4.122Y-3.0512
X5.286Y-3.052
X5.864Y-1.5118
T0
M30
